In [1]:
import pandas as pd
import geopandas as gpd

from pathlib import Path

In [2]:
src_dir = Path('~').expanduser() / 'data/ivs/iww-route-assignment'

In [3]:
df = pd.read_csv(src_dir / 'Telpunten_20260717.csv', sep=';')

In [4]:
df['OBJECT ID'].unique().shape

(745,)

In [5]:
unique_telpunt_df = df.sort_values(by=['OBJECT ID', 'isrsCode']).groupby('OBJECT ID').first()
unique_telpunt_gdf = gpd.GeoDataFrame(unique_telpunt_df, geometry=gpd.points_from_xy(unique_telpunt_df['Longitude'], unique_telpunt_df['Latitude']))
unique_telpunt_gdf = unique_telpunt_gdf.set_crs('EPSG:4326')
unique_telpunt_gdf = unique_telpunt_gdf.to_crs('EPSG:28992')
unique_telpunt_gdf = unique_telpunt_gdf.rename_geometry("point_geometry")

In [6]:
df[df['OBJECT ID'].duplicated(keep=False)]

,Id,type,vaarweg,hectometer,isrsCode,naam,Latitude,Longitude,OBJECT ID
33,1300009,BRUG,13,9,NLGRQ000130331300009,EUVELGUNNERBRUG,52.702053,6.185100,N58B2
34,1300009,BRUG,13,9,NLGRQ000130331300009,EUVELGUNNERBRUG,52.702053,6.185100,N58B4
54,6000008,BLOK,60,8,NaN,BLOK OOSTERHORNKANAAL,53.314600,6.941700,W99OH
55,6000009,BLOK,60,9,NaN,BLOK FARMSUMMERHAVEN,53.314200,6.931100,W99FH
105,8600079,BLOK,86,79,NaN,BLOK HASSELT,52.555327,6.094306,N65BH
...,...,...,...,...,...,...,...,...,...
599,22600323,SLUIS,226,323,NLGOU0226B6551800327,WAAIERSLUIS,52.008978,4.731726,M99DV
736,60000005,BRUG,60,5,NLFAR000600353900005,"Farmsum, brug over bui",53.320589,6.940514,W99FH
738,60000007,BRUG,60,7,NLFAR000600353600007,"Farmsum, brug over bin",53.319316,6.939226,W99OH
778,86000079,BRUG,86,79,NLKAM000840437101079,Stadsbrug Kampen,52.559687,5.919018,N65BH
780,88000003,BRUG,88,3,NLZWS000880439500003,MEPPELERDIEPBRUG,52.637860,6.078169,N66MS

In [7]:
df[df['OBJECT ID'] == 'N67BE'].sort_values(by='isrsCode')

,Id,type,vaarweg,hectometer,isrsCode,naam,Latitude,Longitude,OBJECT ID
127,8800098,BRUG,88,98,NLMEP000880439700098,ESHUISBRUG,52.694466,6.173970,N67BE
125,8800097,BLOK,88,97,NaN,BLOK ESHUISBRUG,52.694429,6.173659,N67BE

In [8]:
df

,Id,type,vaarweg,hectometer,isrsCode,naam,Latitude,Longitude,OBJECT ID
0,100001,BLOK,1,1,NaN,BLOK S1,53.312073,6.850904,N47S1
1,100055,BLOK,1,55,NaN,EEMSKANAAL,53.253820,6.692775,N46BE
2,100181,BLOK,1,181,NaN,EEMSKANAAL,53.303506,6.838693,N47BE
3,100258,SLUIS,1,258,NLFAR000600917800006,FARMSUM,53.319335,6.939505,N47SF
4,200015,BLOK,2,15,NaN,DELFZIJL,53.315300,7.004400,N47BZ
...,...,...,...,...,...,...,...,...,...
777,86000009,BRUG,86,9,NLZWO000860498200009,"Spooldersluis, brug ov",52.509875,6.054616,NIJB5
778,86000079,BRUG,86,79,NLKAM000840437101079,Stadsbrug Kampen,52.559687,5.919018,N65BH
779,86000079,BRUG,86,79,NLKAM000840437101079,Stadsbrug Kampen,52.559687,5.919018,NIJB4
780,88000003,BRUG,88,3,NLZWS000880439500003,MEPPELERDIEPBRUG,52.637860,6.078169,N66MS
781,95000026,BRUG,95,26,NLURK000954369900026,Michiel de Ruyterbrug,52.658037,5.635836,NMRB1

In [9]:
edges_gdf = gpd.read_file('/Users/hemert/projects/iww-route-assignment-sito-is/fis-crawler/output/euris-enriched/edges.geojson')
edges_gdf = edges_gdf.to_crs('EPSG:28992')

In [10]:
edges_gdf

,source,target,name,name_cb,cntrycode,cntrycode_cb,fw_code,fw_code_cb,seq_nr,seq_nr_cb,...,is_border,subgraph,length_m,borderpoint,locode,speed_maxspeed,speed_calspeed,speed_direction,speed_shipcategory,geometry
0,HU_J0001,HU_J0002,Duna,NaN,HU,NaN,00001,NaN,00001,NaN,...,False,0,46249.162541,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (1196372.643 -139594.299, 1196276.0..."
1,HU_J0001,HR_J0002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,True,0,3.447125,HRXXX00001J000214331,HRXXX00001J000214331,NaN,NaN,NaN,NaN,"LINESTRING (1196372.643 -139594.299, 1196372.5..."
2,HU_J0002,HU_J0003,Duna,NaN,HU,NaN,00001,NaN,00002,NaN,...,False,0,101551.900391,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (1199355.261 -108363.882, 1199379.5..."
3,HU_J0002,HU_J0029,Sugovica,NaN,HU,NaN,00011,NaN,00001,NaN,...,False,0,1082.358180,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (1199355.261 -108363.882, 1199408.5..."
4,HU_J0003,HU_J0004,Duna,NaN,HU,NaN,00001,NaN,00003,NaN,...,False,0,7512.740738,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (1185910.987 -14265.483, 1185944.21..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6977,DE_J4002,LU_J4002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,True,0,68.329051,LUMRT10001J400200000,LUMRT10001J400200000,NaN,NaN,NaN,NaN,"LINESTRING (233953.494 190170.323, 233925.177 ..."
6978,DE_J0896,DE_J0895,Mosel,NaN,DE,NaN,03201,03201,00664,00664,...,False,0,16265.390235,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (225417.206 175747.935, 225417.201 ..."
6979,DE_J0895,DE_J0894,Wehrstrecke Grevenmacher,NaN,DE,NaN,03203,03203,00666,00666,...,False,0,664.064116,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (230611.38 187141.05, 230622.718 18..."
6980,LU_J4001,LU_J4002,Hafen Mertert,NaN,LU,NaN,10001,NaN,00001,NaN,...,False,0,1043.821771,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (233001.047 189802.136, 233716.187 ..."
6981,HR_D0014,HR_D0023,Drava,NaN,HR,NaN,00002,NaN,00140,NaN,...,False,0,8975.517300,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (1199162.573 -179930.057, 1199080.2..."

In [19]:
joined_gdf = unique_telpunt_gdf.sjoin_nearest(edges_gdf, how='left', distance_col='distance_join').reset_index()
joined_gdf.sort_values(by=['OBJECT ID', 'distance_join']).groupby('OBJECT ID').first().sort_values(by='distance_join')
joined_gdf["geometry"] = joined_gdf["index_right"].map(edges_gdf.geometry)
joined_gdf = joined_gdf.set_geometry("geometry")
joined_gdf = gpd.GeoDataFrame(
    joined_gdf,
    geometry="geometry",
    crs=edges_gdf.crs,
)
joined_gdf["point_wkt"] = joined_gdf["point_geometry"].to_wkt()

joined_gdf = joined_gdf.drop(columns=["point_geometry"])
joined_gdf.to_csv(src_dir / 'euris_with_telpunt.csv')
joined_gdf.to_file(src_dir / 'euris_with_telpunt.gpkg')

In [17]:
joined_gdf

,OBJECT ID,Id,type,vaarweg,hectometer,isrsCode,naam,Latitude,Longitude,point_geometry,...,subgraph,length_m,borderpoint,locode,speed_maxspeed,speed_calspeed,speed_direction,speed_shipcategory,distance_join,geometry
0,G09HE,11000003,SLUIS,110,3,NLDOR0110A6543000027,HELSLUIS,53.236059,6.650670,POINT (239358.813 584014.566),...,0,260.134746,NaN,NaN,NaN,NaN,NaN,NaN,88.404829,"LINESTRING (239314.372 584091.007, 239092 5839..."
1,G09HN,11000005,BLOK,110,5,NaN,HELKANAAL NOORD,51.812989,4.782217,POINT (113281.588 425102.996),...,0,737.822795,NaN,NaN,NaN,NaN,NaN,NaN,0.079001,"LINESTRING (113334 424593, 113286 424810.001, ..."
2,G09HZ,11000001,BLOK,110,1,NaN,HELKANAAL ZUID,51.808087,4.783158,POINT (113341.947 424557.098),...,0,107.113163,NaN,NaN,NaN,NaN,NaN,NaN,0.030383,"LINESTRING (113366 424491.001, 113342 424557, ..."
3,G09KK,11000011,BLOK,110,11,NaN,KIKVORSKIL,51.801092,4.769834,POINT (112416.465 423786.605),...,0,1018.087717,NaN,NaN,NaN,NaN,NaN,NaN,0.082340,"LINESTRING (112126 423093.001, 112141 423104.0..."
4,G09MD,11000003,SLUIS,110,3,NLDOR0110A6543000027,HELSLUIS,53.236059,6.650670,POINT (239358.813 584014.566),...,0,260.134746,NaN,NaN,NaN,NaN,NaN,NaN,88.404829,"LINESTRING (239314.372 584091.007, 239092 5839..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,Z11BH,12900001,BLOK,129,1,NaN,BUITEN HAVEN,51.511812,4.163882,POINT (70081.706 392135.324),...,0,855.304684,NaN,NaN,NaN,NaN,NaN,NaN,95.458929,"LINESTRING (70672 391971.001, 70184 392166, 70..."
742,Z11TG,12900016,BLOK,129,16,NaN,THOLENSE GAT OOST,51.500345,4.213497,POINT (73505.056 390803.042),...,0,1168.274962,NaN,NaN,NaN,NaN,NaN,NaN,0.007802,"LINESTRING (73965.15 390445.694, 73804.817 390..."
743,Z13BU,31400155,BLOK,314,155,NaN,VEERE BL BUITENHAVEN,51.547177,3.671436,POINT (35994.316 396758.194),...,0,727.581035,NaN,NaN,NaN,NaN,NaN,NaN,0.007294,"LINESTRING (35771 396475, 35799 396541, 36031 ..."
744,Z13KW,13400133,BLOK,134,133,NaN,KAN DOOR WALCHEREN N,51.519472,3.659053,POINT (35062.422 393696.912),...,0,4880.957834,NaN,NaN,NaN,NaN,NaN,NaN,0.055202,"LINESTRING (33781.549 392263.132, 34951 393577..."
745,Z13VE,13400149,SLUIS,134,149,NLVER001340946900149,SL VEERE,51.541476,3.667384,POINT (35698.341 396130.704),...,0,4880.957834,NaN,NaN,NaN,NaN,NaN,NaN,11.975078,"LINESTRING (33781.549 392263.132, 34951 393577..."

In [13]:
unique_telpunt_gdf

,Id,type,vaarweg,hectometer,isrsCode,naam,Latitude,Longitude,point_geometry
OBJECT ID,,,,,,,,,
G09HE,11000003,SLUIS,110,3,NLDOR0110A6543000027,HELSLUIS,53.236059,6.650670,POINT (239358.813 584014.566)
G09HN,11000005,BLOK,110,5,NaN,HELKANAAL NOORD,51.812989,4.782217,POINT (113281.588 425102.996)
G09HZ,11000001,BLOK,110,1,NaN,HELKANAAL ZUID,51.808087,4.783158,POINT (113341.947 424557.098)
G09KK,11000011,BLOK,110,11,NaN,KIKVORSKIL,51.801092,4.769834,POINT (112416.465 423786.605)
G09MD,11000003,SLUIS,110,3,NLDOR0110A6543000027,HELSLUIS,53.236059,6.650670,POINT (239358.813 584014.566)
...,...,...,...,...,...,...,...,...,...
Z11BH,12900001,BLOK,129,1,NaN,BUITEN HAVEN,51.511812,4.163882,POINT (70081.706 392135.324)
Z11TG,12900016,BLOK,129,16,NaN,THOLENSE GAT OOST,51.500345,4.213497,POINT (73505.056 390803.042)
Z13BU,31400155,BLOK,314,155,NaN,VEERE BL BUITENHAVEN,51.547177,3.671436,POINT (35994.316 396758.194)
Z13KW,13400133,BLOK,134,133,NaN,KAN DOOR WALCHEREN N,51.519472,3.659053,POINT (35062.422 393696.912)
Z13VE,13400149,SLUIS,134,149,NLVER001340946900149,SL VEERE,51.541476,3.667384,POINT (35698.341 396130.704)

In [14]:
edges_gdf

,source,target,name,name_cb,cntrycode,cntrycode_cb,fw_code,fw_code_cb,seq_nr,seq_nr_cb,...,is_border,subgraph,length_m,borderpoint,locode,speed_maxspeed,speed_calspeed,speed_direction,speed_shipcategory,geometry
0,HU_J0001,HU_J0002,Duna,NaN,HU,NaN,00001,NaN,00001,NaN,...,False,0,46249.162541,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (1196372.643 -139594.299, 1196276.0..."
1,HU_J0001,HR_J0002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,True,0,3.447125,HRXXX00001J000214331,HRXXX00001J000214331,NaN,NaN,NaN,NaN,"LINESTRING (1196372.643 -139594.299, 1196372.5..."
2,HU_J0002,HU_J0003,Duna,NaN,HU,NaN,00001,NaN,00002,NaN,...,False,0,101551.900391,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (1199355.261 -108363.882, 1199379.5..."
3,HU_J0002,HU_J0029,Sugovica,NaN,HU,NaN,00011,NaN,00001,NaN,...,False,0,1082.358180,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (1199355.261 -108363.882, 1199408.5..."
4,HU_J0003,HU_J0004,Duna,NaN,HU,NaN,00001,NaN,00003,NaN,...,False,0,7512.740738,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (1185910.987 -14265.483, 1185944.21..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6977,DE_J4002,LU_J4002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,True,0,68.329051,LUMRT10001J400200000,LUMRT10001J400200000,NaN,NaN,NaN,NaN,"LINESTRING (233953.494 190170.323, 233925.177 ..."
6978,DE_J0896,DE_J0895,Mosel,NaN,DE,NaN,03201,03201,00664,00664,...,False,0,16265.390235,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (225417.206 175747.935, 225417.201 ..."
6979,DE_J0895,DE_J0894,Wehrstrecke Grevenmacher,NaN,DE,NaN,03203,03203,00666,00666,...,False,0,664.064116,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (230611.38 187141.05, 230622.718 18..."
6980,LU_J4001,LU_J4002,Hafen Mertert,NaN,LU,NaN,10001,NaN,00001,NaN,...,False,0,1043.821771,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (233001.047 189802.136, 233716.187 ..."
6981,HR_D0014,HR_D0023,Drava,NaN,HR,NaN,00002,NaN,00140,NaN,...,False,0,8975.517300,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (1199162.573 -179930.057, 1199080.2..."